<?php require_once __DIR__.'/professional_assets/bootstrap_portal.php'; require_role(['admin','doctor','worker']);
$u=p_user(); $today=date('Y-m-d'); $msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $date=$_POST['attendance_date']??$today;$status=$_POST['status']??'Present';$in=$_POST['check_in']??date('H:i');$out=$_POST['check_out']??null;$note=trim($_POST['note']??'');$marked=$u['role']==='admin'?'Admin': 'Self';
 if($u['role']==='doctor'){$did=(int)$u['id'];$q=$con->prepare("INSERT INTO attendance(role_type,doctorid,attendance_date,check_in,check_out,status,marked_by,note) VALUES('doctor',?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE check_in=VALUES(check_in),check_out=VALUES(check_out),status=VALUES(status),marked_by=VALUES(marked_by),note=VALUES(note)");$q->bind_param('issssss',$did,$date,$in,$out,$status,$marked,$note);$q->execute();}
 elseif($u['role']==='worker'){$wid=(int)$u['id'];$q=$con->prepare("INSERT INTO attendance(role_type,worker_id,attendance_date,check_in,check_out,status,marked_by,note) VALUES('worker',?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE check_in=VALUES(check_in),check_out=VALUES(check_out),status=VALUES(status),marked_by=VALUES(marked_by),note=VALUES(note)");$q->bind_param('issssss',$wid,$date,$in,$out,$status,$marked,$note);$q->execute();}
 else { $kind=$_POST['role_type']??'doctor';$id=(int)$_POST['person_id'];$q=$con->prepare("INSERT INTO attendance(role_type,doctorid,worker_id,attendance_date,check_in,check_out,status,marked_by,note) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE check_in=VALUES(check_in),check_out=VALUES(check_out),status=VALUES(status),marked_by=VALUES(marked_by),note=VALUES(note)");$d=$kind==='doctor'?$id:null;$w=$kind==='worker'?$id:null;$q->bind_param('siissssss',$kind,$d,$w,$date,$in,$out,$status,$marked,$note);$q->execute();}
 log_action($con,'Attendance','Marked '.$status.' on '.$date);$msg='Attendance saved successfully.';
}
$people=[];if($u['role']==='admin'){$r=$con->query("SELECT doctorid id,doctorname name,'doctor' role_type FROM doctor WHERE status='Active' UNION ALL SELECT worker_id id,worker_name name,'worker' role_type FROM workers WHERE status='Active' ORDER BY name");while($x=$r->fetch_assoc())$people[]=$x;}
$rows=$con->query("SELECT a.*,COALESCE(d.doctorname,w.worker_name) name FROM attendance a LEFT JOIN doctor d ON a.doctorid=d.doctorid LEFT JOIN workers w ON a.worker_id=w.worker_id ORDER BY attendance_date DESC,created_at DESC LIMIT 100");
?><!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="professional_assets/app.css"><link rel="stylesheet" href="professional_assets/theme.css.php"><title>Attendance</title></head><body class="module-body"><div class="module-wrap"><div class="module-head"><div><span class="eyebrow">STAFF</span><h1>Attendance</h1><p>Admin can mark staff attendance; doctors and workers can check themselves in.</p></div></div><?php if($msg):?><div class="success"><?php echo esc($msg);?></div><?php endif;?><div class="panel"><h2>Mark attendance</h2><form method="post" class="form-grid"><?php if($u['role']==='admin'):?><label>Staff<select name="person_id" required><?php foreach($people as $x):?><option value="<?php echo $x['id'];?>" data-role="<?php echo $x['role_type'];?>"><?php echo esc($x['name'].' ('.$x['role_type'].')');?></option><?php endforeach;?></select></label><input type="hidden" name="role_type" id="role_type" value="doctor"><?php endif;?><label>Date<input type="date" name="attendance_date" value="<?php echo $today;?>"></label><label>Status<select name="status"><option>Present</option><option>Late</option><option>Absent</option><option>Leave</option></select></label><label>Check in<input type="time" name="check_in" value="<?php echo date('H:i');?>"></label><label>Check out<input type="time" name="check_out"></label><label>Note<input name="note" placeholder="Optional note"></label><button class="primary-btn" type="submit">Save Attendance</button></form></div><div class="panel"><h2>Recent attendance</h2><div class="table-scroll"><table><tr><th>Date</th><th>Staff</th><th>Role</th><th>In</th><th>Out</th><th>Status</th><th>Marked by</th></tr><?php while($r=$rows->fetch_assoc()):?><tr><td><?php echo esc($r['attendance_date']);?></td><td><?php echo esc($r['name']??'');?></td><td><?php echo esc($r['role_type']);?></td><td><?php echo esc($r['check_in']??'');?></td><td><?php echo esc($r['check_out']??'');?></td><td><?php echo esc($r['status']);?></td><td><?php echo esc($r['marked_by']);?></td></tr><?php endwhile;?></table></div></div></div><script>document.querySelector('select[name="person_id"]')?.addEventListener('change',function(){document.getElementById('role_type').value=this.options[this.selectedIndex].dataset.role;});</script></body></html>