<?php
declare(strict_types=1); session_start(); require_once __DIR__.'/dbconnection.php';
function countRows(mysqli $c,string $sql):int{try{$r=$c->query($sql);return (int)$r->fetch_row()[0];}catch(Throwable $e){return 0;}}
function money(mysqli $c,float $n):string{$s=$c->query("SELECT currency FROM hospital_settings WHERE setting_id=1");$cur=$s?$s->fetch_assoc()['currency']:'AFN';return $cur.' '.number_format($n,2);}
$loginError='';$loginRole=$_POST['role']??'';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='login'){
 $login=trim((string)($_POST['login']??''));$password=(string)($_POST['password']??'');
 $map=['admin'=>['admin','adminid','loginid','adminname'],'doctor'=>['doctor','doctorid','loginid','doctorname'],'patient'=>['patient','patientid','loginid','patientname'],'worker'=>['workers','worker_id','loginid','worker_name']];
 if($login===''||$password===''||!isset($map[$loginRole]))$loginError='Please choose a role and enter your username and password.';else{$t=$map[$loginRole];$q=$con->prepare("SELECT * FROM `{$t[0]}` WHERE `{$t[2]}`=? AND `status`='Active' LIMIT 1");$q->bind_param('s',$login);$q->execute();$account=$q->get_result()->fetch_assoc();
  if($account && (password_verify($password,(string)$account['password'])||hash_equals((string)$account['password'],$password))){session_regenerate_id(true);$_SESSION['portal_role']=$loginRole;$_SESSION[$t[1]]=(int)$account[$t[1]];$_SESSION['portal_id']=(int)$account[$t[1]];$_SESSION['portal_name']=$account[$t[3]];$_SESSION['portal_login']=$login;if(!password_get_info((string)$account['password'])['algo']){$h=password_hash($password,PASSWORD_DEFAULT);$u=$con->prepare("UPDATE `{$t[0]}` SET password=? WHERE `{$t[1]}`=?");$id=(int)$account[$t[1]];$u->bind_param('si',$h,$id);$u->execute();}}
  else $loginError='Invalid username or password, or the account is inactive.';
 }
}
$loggedIn=isset($_SESSION['portal_role']);$role=$_SESSION['portal_role']??'';$name=$_SESSION['portal_name']??'User';
$settings=['hospital_name'=>'Station Hospital','hospital_logo'=>'','currency'=>'AFN'];try{$r=$con->query("SELECT * FROM hospital_settings WHERE setting_id=1");if($r&&$r->num_rows)$settings=$r->fetch_assoc();}catch(Throwable $e){}
if($loggedIn){
 $stats=['Patients'=>countRows($con,"SELECT COUNT(*) FROM patient WHERE status='Active'"),'Doctors'=>countRows($con,"SELECT COUNT(*) FROM doctor WHERE status='Active'"),'Appointments'=>countRows($con,"SELECT COUNT(*) FROM appointment WHERE status='Active'"),'Departments'=>countRows($con,"SELECT COUNT(*) FROM department WHERE status='Active'")];
 if($role==='admin'){ $stats['Medicines']=countRows($con,"SELECT COUNT(*) FROM pharmacy_medicines WHERE status='Active'"); $stats['Low Stock']=countRows($con,"SELECT COUNT(*) FROM pharmacy_medicines WHERE status='Active' AND quantity<=reorder_level"); $stats['Out of Stock']=countRows($con,"SELECT COUNT(*) FROM pharmacy_medicines WHERE status='Active' AND quantity<=0"); $stats['Expired Medicines']=countRows($con,"SELECT COUNT(*) FROM pharmacy_medicines WHERE expiry_date IS NOT NULL AND expiry_date<CURDATE() AND quantity>0"); $stats['Pharmacy Outgoing']=countRows($con,"SELECT COALESCE(SUM(quantity),0) FROM pharmacy_transactions WHERE transaction_type='outgoing' AND DATE(transaction_date)=CURDATE()"); $stats['Pharmacy Incoming']=countRows($con,"SELECT COALESCE(SUM(quantity),0) FROM pharmacy_transactions WHERE transaction_type='incoming' AND DATE(transaction_date)=CURDATE()"); $stats['Expiring Soon']=countRows($con,"SELECT COUNT(*) FROM pharmacy_medicines WHERE expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY)"); }
 if($role==='doctor')$stats=['My Appointments'=>countRows($con,"SELECT COUNT(*) FROM appointment WHERE doctorid=".(int)$_SESSION['doctorid']),'My Patients'=>countRows($con,"SELECT COUNT(DISTINCT patientid) FROM appointment WHERE doctorid=".(int)$_SESSION['doctorid'])];
 if($role==='patient')$stats=['My Appointments'=>countRows($con,"SELECT COUNT(*) FROM appointment WHERE patientid=".(int)$_SESSION['patientid']),'My Treatments'=>countRows($con,"SELECT COUNT(*) FROM treatment_records WHERE patientid=".(int)$_SESSION['patientid']),'My Prescriptions'=>countRows($con,"SELECT COUNT(*) FROM prescription WHERE patientid=".(int)$_SESSION['patientid'])];
 if($role==='worker')$stats=['My Attendance'=>countRows($con,"SELECT COUNT(*) FROM attendance WHERE worker_id=".(int)$_SESSION['worker_id']), 'Attendance This Month'=>countRows($con,"SELECT COUNT(*) FROM attendance WHERE worker_id=".(int)$_SESSION['worker_id']." AND MONTH(attendance_date)=MONTH(CURDATE())")];
 $year=(int)($_GET['year']??date('Y')); if($year<2000||$year>2100)$year=(int)date('Y');
 $monthly=array_fill(1,12,0.0);$yrTotals=[];
 try{$res=$con->query("SELECT MONTH(transaction_date) m,SUM(amount) total FROM financial_transactions WHERE transaction_type='patient_fee' AND YEAR(transaction_date)={$year} AND status='Paid' GROUP BY MONTH(transaction_date)");while($x=$res->fetch_assoc())$monthly[(int)$x['m']] = (float)$x['total'];
  $res=$con->query("SELECT YEAR(transaction_date) y,SUM(CASE WHEN transaction_type='patient_fee' THEN amount ELSE 0 END) income,SUM(CASE WHEN transaction_type='doctor_salary' THEN amount ELSE 0 END) expense FROM financial_transactions GROUP BY YEAR(transaction_date) ORDER BY y");while($x=$res->fetch_assoc())$yrTotals[(int)$x['y']] = ['income'=>(float)$x['income'],'expense'=>(float)$x['expense']];
 }catch(Throwable $e){}
 $income=array_sum($monthly);$expense=0;try{$r=$con->query("SELECT COALESCE(SUM(amount),0) FROM salary_payments WHERE YEAR(payment_date)={$year}");$expense=(float)$r->fetch_row()[0];}catch(Throwable $e){}
}
$logo=$settings['hospital_logo']??'';$hospital=$settings['hospital_name']??'Station Hospital';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo htmlspecialchars($hospital);?> | HMS</title><link rel="stylesheet" href="professional_assets/app.css"><link rel="stylesheet" href="professional_assets/theme.css.php"><link rel="stylesheet" href="css/font-awesome.css"></head>
<body data-theme="light">
<?php if(!$loggedIn): ?>
<div class="portal-login">
 <div class="login-top"><div class="login-brand"><?php if($logo):?><img src="<?php echo htmlspecialchars($logo);?>" class="hospital-logo" alt="Logo"><?php else:?><div class="brand-mark">+</div><?php endif;?><div><strong><?php echo htmlspecialchars($hospital);?></strong><span data-i="subtitle">Hospital Management System</span></div></div><div class="portal-tools"><button class="tool-btn" id="themeBtn">◐ <span data-i="theme">Dark / Light</span></button><select id="languageSelect" class="language-select"><option value="en">English</option><option value="ps">پښتو</option><option value="fa">دری</option></select></div></div>
 <div class="welcome"><span class="eyebrow" data-i="secure">SECURE MANAGEMENT PORTAL</span><h1 data-i="welcome">Welcome to your hospital workspace</h1><p data-i="welcomeText">One modern portal for administrators, doctors, patients and staff.</p></div>
 <div class="login-card">
  <div class="login-card-head"><span class="eyebrow" data-i="signIn">SIGN IN</span><h2 data-i="selectAccount">Sign in to your account</h2><p data-i="chooseRole">Enter your username and password, then select your role.</p></div>
  <?php if($loginError):?><div class="alert"><?php echo htmlspecialchars($loginError);?></div><?php endif;?>
  <form method="post" class="login-form"><input type="hidden" name="action" value="login">
   <label data-i="username">Username / Login ID<input name="login" required autocomplete="username" placeholder="Enter your login ID"></label>
   <label data-i="password">Password<input type="password" name="password" required autocomplete="current-password" placeholder="Enter your password"></label>
   <label data-i="roleLabel">Account role<select name="role" id="roleInput" required><option value="" disabled <?php echo $loginRole===''?'selected':'';?>>Select your role</option><option value="admin" <?php echo $loginRole==='admin'?'selected':'';?>>Administrator</option><option value="doctor" <?php echo $loginRole==='doctor'?'selected':'';?>>Doctor</option><option value="patient" <?php echo $loginRole==='patient'?'selected':'';?>>Patient / User</option><option value="worker" <?php echo $loginRole==='worker'?'selected':'';?>>Worker / Staff</option></select></label>
   <button class="primary-btn" type="submit" data-i="signInBtn">Sign in to portal →</button>
  </form>
  <div class="login-links"><a href="patient-register.php" data-i="createPatient">Create a patient account</a><span>•</span><span data-i="offline">Works offline with local XAMPP/MySQL</span></div>
 </div>
 <div class="login-footer">© <?php echo date('Y');?> <?php echo htmlspecialchars($hospital);?> · <span data-i="offline2">Offline-ready hospital portal</span></div>
</div>
<script src="professional_assets/portal.js"></script>
<?php else: ?>
<div class="app-shell">
 <aside class="sidebar" id="sidebar"><div class="side-brand"><?php if($logo):?><img src="<?php echo htmlspecialchars($logo);?>" class="hospital-logo small" alt="Logo"><?php else:?><div class="brand-mark">+</div><?php endif;?><div><b><?php echo htmlspecialchars($hospital);?></b><span>HMS</span></div></div><div class="profile-mini"><div class="avatar"><?php echo strtoupper(substr($name,0,1));?></div><div><b><?php echo htmlspecialchars($name);?></b><small><?php echo ucfirst($role);?></small></div></div>
 <nav>
  <a class="nav-item active" href="#" data-view="dashboard"><span>⌂</span><span data-i="dashboard">Dashboard</span></a>
  <?php if($role==='admin'):?>
   <details class="nav-group" open><summary>♟ <span data-i="patientMenu">Patients</span></summary><a class="nav-item sub" href="#" data-view="viewpatient.php"><span>♟</span><span>View Patients</span></a><a class="nav-item sub" href="#" data-view="patient.php"><span>＋</span><span>Add Patient</span></a><a class="nav-item sub" href="#" data-view="medical-records.php"><span>▤</span><span>Medical Records</span></a></details>
   <details class="nav-group"><summary>✚ <span data-i="doctorMenu">Doctors</span></summary><a class="nav-item sub" href="#" data-view="doctor.php"><span>＋</span><span>Add Doctor</span></a><a class="nav-item sub" href="#" data-view="viewdoctor.php"><span>✚</span><span>View Doctors</span></a><a class="nav-item sub" href="#" data-view="doctortimings.php"><span>◴</span><span>Add Doctor Timing</span></a><a class="nav-item sub" href="#" data-view="viewdoctortimings.php"><span>◷</span><span>View Doctor Timings</span></a><a class="nav-item sub" href="#" data-view="attendance.php"><span>◷</span><span>Doctor Attendance</span></a></details>
   <details class="nav-group"><summary>◷ <span data-i="appointmentMenu">Appointments</span></summary><a class="nav-item sub" href="#" data-view="appointment.php"><span>＋</span><span>New Appointment</span></a><a class="nav-item sub" href="#" data-view="viewappointmentpending.php"><span>◷</span><span>Pending</span></a><a class="nav-item sub" href="#" data-view="viewappointmentapproved.php"><span>✓</span><span>Approved</span></a><a class="nav-item sub" href="#" data-view="appointmentapproval.php"><span>✓</span><span>Approval</span></a></details>
   <details class="nav-group"><summary>🛏 <span>Admissions</span></summary><a class="nav-item sub" href="#" data-view="admissions.php"><span>＋</span><span>Admit Patient</span></a><a class="nav-item sub" href="#" data-view="admissions.php"><span>▤</span><span>Admission History</span></a><a class="nav-item sub" href="#" data-view="admissions.php"><span>▣</span><span>Ward / Room / Bed</span></a></details>
   <details class="nav-group" open><summary>💊 <span>Pharmacy</span></summary><a class="nav-item sub" href="#" data-view="pharmacy.php"><span>💊</span><span>Pharmacy Dashboard</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php"><span>＋</span><span>Add Medicine</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php"><span>▣</span><span>Medicine List / Stock</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php"><span>↓</span><span>Incoming / Purchase</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php"><span>↑</span><span>Outgoing / Dispensing</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php?filter=low"><span>⚠</span><span>Low Stock</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php?filter=expired"><span>!</span><span>Expired Medicines</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php?filter=expiring"><span>◷</span><span>Near Expiry</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php"><span>↩</span><span>Returns / Adjustments</span></a><a class="nav-item sub" href="#" data-view="pharmacy.php"><span>▤</span><span>Stock History</span></a></details>
   <details class="nav-group"><summary>🧪 <span>Laboratory</span></summary><a class="nav-item sub" href="#" data-view="laboratory.php"><span>＋</span><span>Add Test / Request</span></a><a class="nav-item sub" href="#" data-view="laboratory.php"><span>◷</span><span>Pending Tests</span></a><a class="nav-item sub" href="#" data-view="laboratory.php"><span>✓</span><span>Completed / Results</span></a><a class="nav-item sub" href="#" data-view="laboratory.php"><span>▤</span><span>Lab Reports</span></a></details>
   <details class="nav-group"><summary>🚑 <span>Emergency</span></summary><a class="nav-item sub" href="#" data-view="emergency.php"><span>＋</span><span>Emergency Registration</span></a><a class="nav-item sub" href="#" data-view="emergency.php"><span>!</span><span>Triage / Priority</span></a><a class="nav-item sub" href="#" data-view="emergency.php"><span>✚</span><span>Emergency Queue</span></a></details>
   <details class="nav-group"><summary>💳 <span>Billing & Payments</span></summary><a class="nav-item sub" href="#" data-view="billing.php"><span>＋</span><span>Patient Invoice</span></a><a class="nav-item sub" href="#" data-view="billing.php"><span>▤</span><span>Payment History</span></a><a class="nav-item sub" href="#" data-view="billing.php"><span>✓</span><span>Paid / Unpaid</span></a><a class="nav-item sub" href="#" data-view="finance.php"><span>¤</span><span>Daily Revenue</span></a></details>
   <details class="nav-group"><summary>🩻 <span>Radiology</span></summary><a class="nav-item sub" href="#" data-view="radiology.php"><span>＋</span><span>New Request</span></a><a class="nav-item sub" href="#" data-view="radiology.php"><span>◷</span><span>Pending Reports</span></a><a class="nav-item sub" href="#" data-view="radiology.php"><span>✓</span><span>Completed Reports</span></a></details>
   <details class="nav-group"><summary>👩‍⚕ <span>Nursing</span></summary><a class="nav-item sub" href="#" data-view="nursing.php"><span>◉</span><span>Nursing Workspace</span></a><a class="nav-item sub" href="#" data-view="nursing.php"><span>♡</span><span>Vital Signs / Notes</span></a></details>
   <details class="nav-group"><summary>📦 <span>General Inventory</span></summary><a class="nav-item sub" href="#" data-view="inventory.php"><span>＋</span><span>Add Inventory</span></a><a class="nav-item sub" href="#" data-view="inventory.php"><span>▣</span><span>Current Stock</span></a><a class="nav-item sub" href="#" data-view="inventory.php"><span>↕</span><span>Incoming / Outgoing</span></a></details>
   <details class="nav-group"><summary>▦ <span data-i="departmentMenu">Departments</span></summary><a class="nav-item sub" href="#" data-view="department.php"><span>＋</span><span>Add Department</span></a><a class="nav-item sub" href="#" data-view="viewdepartment.php"><span>▦</span><span>View Departments</span></a><a class="nav-item sub" href="#" data-view="departmentDoctor.php"><span>✚</span><span>Department Doctors</span></a></details>
   <details class="nav-group"><summary>◉ <span data-i="staffMenu">Staff</span></summary><a class="nav-item sub" href="#" data-view="workers.php"><span>◈</span><span>Workers</span></a><a class="nav-item sub" href="#" data-view="attendance.php"><span>◷</span><span>Attendance</span></a></details>
   <details class="nav-group"><summary>¤ <span data-i="financeMenu">Finance</span></summary><a class="nav-item sub" href="#" data-view="finance.php"><span>¤</span><span>Fees & Salaries</span></a><a class="nav-item sub" href="#" data-view="billing.php"><span>💳</span><span>Billing & Payments</span></a></details>
   <details class="nav-group"><summary>⚙ <span data-i="settingsMenu">Settings</span></summary><a class="nav-item sub" href="#" data-view="settings.php"><span>⚙</span><span>Hospital Settings</span></a><a class="nav-item sub" href="#" data-view="backup.php"><span>↓</span><span>Backup & Restore</span></a></details>
   <details class="nav-group"><summary>🔐 <span>Security</span></summary><a class="nav-item sub" href="#" data-view="audit-log.php"><span>▤</span><span>Activity / Audit Log</span></a></details>
   <details class="nav-group"><summary>◉ <span>Admin Information</span></summary><a class="nav-item sub" href="#" data-view="adminprofile.php"><span>◉</span><span>Admin Profile</span></a><a class="nav-item sub" href="#" data-view="adminchangepassword.php"><span>🔒</span><span>Change Password</span></a><a class="nav-item sub" href="#" data-view="addadmin.php"><span>＋</span><span>Add Admin</span></a><a class="nav-item sub" href="#" data-view="viewadmins.php"><span>☷</span><span>View Admins</span></a></details>
  <?php elseif($role==='doctor'):?>
   <details class="nav-group" open><summary>✚ <span data-i="doctorMenu">Doctor</span></summary><a class="nav-item sub" href="#" data-view="dashboard"><span>⌂</span><span data-i="doctorHome">Doctor Home</span></a><a class="nav-item sub" href="#" data-view="doctorprofile.php"><span>◉</span><span data-i="doctorProfile">Profile</span></a><a class="nav-item sub" href="#" data-view="viewappointment.php"><span>◷</span><span data-i="appointments">Appointments</span></a><a class="nav-item sub" href="#" data-view="viewpatient.php"><span>♟</span><span data-i="patients">Patients</span></a><a class="nav-item sub" href="#" data-view="prescription.php"><span>▤</span><span data-i="prescriptions">Prescriptions</span></a><a class="nav-item sub" href="#" data-view="doctortimings.php"><span>◴</span><span data-i="doctorSchedule">Schedule</span></a><a class="nav-item sub" href="#" data-view="attendance.php"><span>◷</span><span data-i="attendance">Attendance</span></a></details>
  <?php elseif($role==='worker'):?>
   <details class="nav-group" open><summary>◈ <span data-i="workerMenu">Worker</span></summary><a class="nav-item sub" href="#" data-view="dashboard"><span>⌂</span><span data-i="workerHome">Worker Home</span></a><a class="nav-item sub" href="#" data-view="profile-settings.php"><span>◉</span><span data-i="myProfile">Profile</span></a><a class="nav-item sub" href="#" data-view="attendance.php"><span>◷</span><span data-i="attendance">Attendance</span></a></details>
  <?php else:?>
   <details class="nav-group" open><summary>♟ <span data-i="patientMenu">Patient</span></summary><a class="nav-item sub" href="#" data-view="dashboard"><span>⌂</span><span data-i="patientHome">Patient Home</span></a><a class="nav-item sub" href="#" data-view="patientprofile.php"><span>◉</span><span data-i="patientProfile">Profile</span></a><a class="nav-item sub" href="#" data-view="patientappointment.php"><span>◷</span><span data-i="patientAppointments">Appointments</span></a><a class="nav-item sub" href="#" data-view="viewdoctor.php"><span>✚</span><span data-i="patientDoctors">Doctors</span></a><a class="nav-item sub" href="#" data-view="orders.php"><span>▣</span><span data-i="patientOrders">Orders</span></a><a class="nav-item sub" href="#" data-view="patient-health.php"><span>♡</span><span data-i="healthRecord">Health Record</span></a><a class="nav-item sub" href="#" data-view="patientprescription.php"><span>▤</span><span data-i="prescriptions">Prescriptions</span></a></details>
  <?php endif;?>
  <?php if($role!=='admin'):?><details class="nav-group"><summary>⚙ <span data-i="settingsMenu">Settings</span></summary><a class="nav-item sub" href="#" data-view="profile-settings.php"><span>◉</span><span data-i="myProfile">Profile Settings</span></a></details><?php endif;?>
 </nav><a class="logout" href="logout.php"><span>↪</span> <span data-i="signOut">Sign out</span></a></aside>
 <main class="main"><header class="topbar"><button class="mobile-menu" id="mobileMenu">☰</button><div><small data-i="hospitalManagement">Hospital Management</small><h2 id="pageTitle" data-i="dashboard">Dashboard</h2></div><div class="top-actions"><button class="tool-btn" id="themeBtn">◐</button><select id="languageSelect" class="language-select"><option value="en">EN</option><option value="ps">PS</option><option value="fa">دری</option></select><span class="status-dot"></span> <span data-i="systemOnline">System Online</span><div class="top-avatar"><?php echo strtoupper(substr($name,0,1));?></div></div></header>
 <section id="dashboardView" class="content"><div class="hero-row"><div><span class="eyebrow" data-i="goodDay">GOOD DAY</span><h1 data-i="hello">Hello, <?php echo htmlspecialchars($name);?> </h1><p data-i="dashboardText">Your workspace is ready. Use the sidebar to manage hospital activities.</p></div><div class="date-card"><b><?php echo date('l');?></b><strong><?php echo date('d M Y');?></strong><small><?php echo htmlspecialchars($hospital);?></small></div></div>
 <div class="stat-grid"><?php foreach($stats as $label=>$value):?><div class="stat-card"><span><?php echo htmlspecialchars($label);?></span><strong><?php echo $value;?></strong><small data-i="currentRecords">Current records</small></div><?php endforeach;if($role==='admin'):?><div class="stat-card finance-stat"><span data-i="patientFees">Patient fees</span><strong><?php echo htmlspecialchars($settings['currency']);?> <?php echo number_format($income,2);?></strong><small><?php echo $year;?></small></div><div class="stat-card finance-stat"><span data-i="doctorSalaries">Doctor salaries</span><strong><?php echo htmlspecialchars($settings['currency']);?> <?php echo number_format($expense,2);?></strong><small><?php echo $year;?></small></div><?php endif;?></div>
 <?php if($role==='admin'):?><div class="analytics-grid"><div class="chart-card"><div class="chart-head"><div><h2 data-i="monthlyFees">Monthly patient fees</h2><p data-i="selectedYear">Selected year</p></div><form><select name="year" onchange="this.form.submit()"><?php for($y=date('Y');$y>=date('Y')-5;$y--):?><option value="<?php echo $y;?>" <?php echo $y===$year?'selected':'';?>><?php echo $y;?></option><?php endfor;?></select></form></div><div class="bars"><?php $months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];$max=max($monthly);foreach($monthly as $i=>$v):$h=$max?max(4,round($v/$max*100)):4;?><div class="bar-col"><div class="bar-value"><?php echo number_format($v,0);?></div><div class="bar" style="height:<?php echo $h;?>%"></div><small><?php echo $months[$i-1];?></small></div><?php endforeach;?></div><div class="line-chart"><svg viewBox="0 0 600 180" preserveAspectRatio="none"><polyline points="<?php $pts=[];$max2=max($monthly);foreach($monthly as $i=>$v){$x=25+($i-1)*50;$y=160-($max2?($v/$max2*130):0);$pts[]=round($x).",".round($y);}echo implode(" ",$pts);?>" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg></div></div><div class="chart-card"><h2 data-i="yearlyFinance">Yearly financial overview</h2><p data-i="incomeExpense">Patient fees vs doctor salaries</p><div class="year-list"><?php if(!$yrTotals):?><div class="empty">No financial transactions yet.</div><?php else:foreach($yrTotals as $y=>$v):?><div class="year-row"><b><?php echo $y;?></b><span class="income">+ <?php echo htmlspecialchars($settings['currency']);?> <?php echo number_format($v['income'],0);?></span><span class="expense">− <?php echo htmlspecialchars($settings['currency']);?> <?php echo number_format($v['expense'],0);?></span></div><?php endforeach;endif;?></div></div></div><?php endif;?>
 <div class="section-head"><div><h2 data-i="quickActions">Quick actions</h2><p data-i="commonTasks">Open common tasks directly from your dashboard.</p></div></div><div class="quick-grid"><?php $quick=$role==='admin'?[['viewpatient.php','Add / View Patients','Patient records'],['viewdoctor.php','Doctors','Medical staff'],['viewappointment.php','Appointments','Schedule & approvals'],['pharmacy.php','Pharmacy','Medicine stock, incoming & outgoing'],['finance.php','Finance & Fees','Patient income and doctor salaries']]:($role==='doctor'?[['viewappointment.php','Appointments','Review today'],['viewpatient.php','Patients','Patient records'],['prescription.php','Prescriptions','Create prescriptions'],['attendance.php','Attendance','Mark your attendance']]:($role==='worker'?[['attendance.php','Attendance','Check in / check out'],['profile-settings.php','My Profile','Your staff account']]:[['appointment.php','Book Appointment','Request a visit'],['patientappointment.php','My Appointments','Upcoming visits'],['patient-health.php','My Health Record','Diseases and treatments'],['patientprescription.php','Prescriptions','Your medicines']]));foreach($quick as $q):?><a href="#" class="quick-card" data-view="<?php echo $q[0];?>"><span class="quick-icon">+</span><b><?php echo htmlspecialchars($q[1]);?></b><small><?php echo htmlspecialchars($q[2]);?></small><em>Open →</em></a><?php endforeach;?></div></section>
 <section id="workspace" class="workspace" hidden><div class="workspace-head"><div><span class="eyebrow" data-i="module">MODULE</span><h3 id="workspaceTitle">Hospital module</h3></div><a id="exportBtn" class="secondary-btn" href="#" target="_blank" rel="noopener">↓ <span data-i="downloadExcel">Download Excel</span></a></div><div class="workspace-loading"><div class="spinner"></div><p>Loading module…</p></div><iframe id="moduleFrame" title="Hospital module" loading="lazy"></iframe></section></main></div>
<script>window.PORTAL_ROLE=<?php echo json_encode($role);?>;</script><script src="professional_assets/app.js"></script><script src="professional_assets/i18n.js"></script>
<?php endif; ?></body></html>
