<?php
require_once __DIR__.'/professional_assets/bootstrap_portal.php';
require_role(['admin','worker']);

/* Create the pharmacy data model automatically for existing installations. */
$con->query("CREATE TABLE IF NOT EXISTS pharmacy_medicines (
 id INT AUTO_INCREMENT PRIMARY KEY, medicine_name VARCHAR(120) NOT NULL, generic_name VARCHAR(120) DEFAULT '', category VARCHAR(80) DEFAULT '',
 dosage_form VARCHAR(60) DEFAULT '', strength VARCHAR(60) DEFAULT '', unit VARCHAR(30) DEFAULT 'unit', batch_no VARCHAR(80) DEFAULT '', expiry_date DATE NULL,
 purchase_price DECIMAL(12,2) DEFAULT 0, selling_price DECIMAL(12,2) DEFAULT 0, quantity INT DEFAULT 0, reorder_level INT DEFAULT 0,
 supplier VARCHAR(150) DEFAULT '', status VARCHAR(30) DEFAULT 'Active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(expiry_date), INDEX(quantity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$con->query("CREATE TABLE IF NOT EXISTS pharmacy_transactions (
 id INT AUTO_INCREMENT PRIMARY KEY, medicine_id INT NOT NULL, transaction_type ENUM('incoming','outgoing','adjustment','return') NOT NULL,
 quantity INT NOT NULL, unit_price DECIMAL(12,2) DEFAULT 0, patient_id INT DEFAULT 0, supplier VARCHAR(150) DEFAULT '', reference_no VARCHAR(100) DEFAULT '', doctor_name VARCHAR(120) DEFAULT '', prescription_ref VARCHAR(120) DEFAULT '', note TEXT,
 transaction_date DATETIME DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(100) DEFAULT '', INDEX(medicine_id), INDEX(transaction_type), INDEX(transaction_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
@$con->query("ALTER TABLE pharmacy_transactions ADD COLUMN doctor_name VARCHAR(120) DEFAULT ''");
@$con->query("ALTER TABLE pharmacy_transactions ADD COLUMN prescription_ref VARCHAR(120) DEFAULT ''");

$msg=''; $error='';
if(isset($_GET['delete'])){ $did=(int)$_GET['delete']; $con->query("DELETE FROM pharmacy_medicines WHERE id=$did"); }
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if($action==='add_medicine'){
  $s=$con->prepare("INSERT INTO pharmacy_medicines(medicine_name,generic_name,category,dosage_form,strength,unit,batch_no,expiry_date,purchase_price,selling_price,quantity,reorder_level,supplier,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
  $name=trim($_POST['medicine_name']??'');$generic=trim($_POST['generic_name']??'');$cat=trim($_POST['category']??'');$form=trim($_POST['dosage_form']??'');$strength=trim($_POST['strength']??'');$unit=trim($_POST['unit']??'unit');$batch=trim($_POST['batch_no']??'');$expiry=($_POST['expiry_date']??'')?:null;$buy=(float)($_POST['purchase_price']??0);$sell=(float)($_POST['selling_price']??0);$qty=(int)($_POST['quantity']??0);$reorder=(int)($_POST['reorder_level']??0);$supplier=trim($_POST['supplier']??'');$status='Active';
  if($name===''){$error='Medicine name is required.';}else{$s->bind_param('ssssssssddiiss',$name,$generic,$cat,$form,$strength,$unit,$batch,$expiry,$buy,$sell,$qty,$reorder,$supplier,$status);}
  if(!$error && $s->execute()){$msg='Medicine added successfully.';} elseif(!$error){$error=$s->error;}
 }
 if($action==='edit_medicine'){ $id=(int)($_POST['id']??0);$s=$con->prepare("UPDATE pharmacy_medicines SET medicine_name=?,generic_name=?,category=?,dosage_form=?,strength=?,unit=?,batch_no=?,expiry_date=?,purchase_price=?,selling_price=?,quantity=?,reorder_level=?,supplier=?,status=? WHERE id=?");$name=trim($_POST['medicine_name']);$generic=trim($_POST['generic_name']);$cat=trim($_POST['category']);$form=trim($_POST['dosage_form']);$strength=trim($_POST['strength']);$unit=trim($_POST['unit']);$batch=trim($_POST['batch_no']);$expiry=$_POST['expiry_date']?:null;$buy=(float)$_POST['purchase_price'];$sell=(float)$_POST['selling_price'];$qty=(int)$_POST['quantity'];$reorder=(int)$_POST['reorder_level'];$supplier=trim($_POST['supplier']);$status=$_POST['status']??'Active';$s->bind_param('ssssssssddiissi',$name,$generic,$cat,$form,$strength,$unit,$batch,$expiry,$buy,$sell,$qty,$reorder,$supplier,$status,$id);if($s->execute())$msg='Medicine updated.'; }
 if($action==='stock'){
  $mid=(int)($_POST['medicine_id']??0);$type=$_POST['transaction_type']??'incoming';$qty=abs((int)($_POST['quantity']??0));$price=(float)($_POST['unit_price']??0);$patient=(int)($_POST['patient_id']??0);$supplier=trim($_POST['supplier']??'');$ref=trim($_POST['reference_no']??'');$doctor=trim($_POST['doctor_name']??'');$prescription=trim($_POST['prescription_ref']??'');$note=trim($_POST['note']??'');
  if($mid<1||$qty<1||!in_array($type,['incoming','outgoing','adjustment','return'],true)){$error='Select a medicine and enter a valid quantity.';}else{
   $m=$con->prepare('SELECT quantity FROM pharmacy_medicines WHERE id=?');$m->bind_param('i',$mid);$m->execute();$cur=(int)($m->get_result()->fetch_assoc()['quantity']??0);
   $delta=in_array($type,['incoming','return'],true)?$qty:-$qty; if($type==='adjustment')$delta=$qty-$cur;
   if($cur+$delta<0){$error='Insufficient stock for this outgoing transaction.';}else{
    $u=$con->prepare('UPDATE pharmacy_medicines SET quantity=? WHERE id=?');$new=$cur+$delta;$u->bind_param('ii',$new,$mid);$u->execute();
    $s=$con->prepare('INSERT INTO pharmacy_transactions(medicine_id,transaction_type,quantity,unit_price,patient_id,supplier,reference_no,doctor_name,prescription_ref,note,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$who=$_SESSION['portal_login']??'';$s->bind_param('isidisssssss',$mid,$type,$qty,$price,$patient,$supplier,$ref,$doctor,$prescription,$note,$who);$s->execute();$msg='Stock transaction recorded.';
   }
  }
 }
}
$search=trim($_GET['search']??'');$filter=$_GET['filter']??'all';$where='1=1';$params=[];$types='';
if($search!==''){$where.=" AND (medicine_name LIKE ? OR generic_name LIKE ? OR batch_no LIKE ? OR supplier LIKE ?)";$q="%$search%";$params=[$q,$q,$q,$q];$types='ssss';}
if($filter==='low')$where.=' AND quantity<=reorder_level';
if($filter==='expired')$where.=' AND expiry_date IS NOT NULL AND expiry_date<CURDATE()';
if($filter==='expiring')$where.=' AND expiry_date IS NOT NULL AND expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY)';
$sql="SELECT * FROM pharmacy_medicines WHERE $where ORDER BY medicine_name";$stmt=$con->prepare($sql);if($types)$stmt->bind_param($types,...$params);$stmt->execute();$meds=$stmt->get_result();
$patients=$con->query("SELECT patientid,patientname FROM patient WHERE status='Active' ORDER BY patientname");
$incoming=(int)$con->query("SELECT COALESCE(SUM(quantity),0) FROM pharmacy_transactions WHERE transaction_type='incoming' AND DATE(transaction_date)=CURDATE()")->fetch_row()[0];
$outgoing=(int)$con->query("SELECT COALESCE(SUM(quantity),0) FROM pharmacy_transactions WHERE transaction_type='outgoing' AND DATE(transaction_date)=CURDATE()")->fetch_row()[0];
$total=(int)$con->query("SELECT COUNT(*) FROM pharmacy_medicines WHERE status='Active'")->fetch_row()[0];$low=(int)$con->query("SELECT COUNT(*) FROM pharmacy_medicines WHERE status='Active' AND quantity<=reorder_level")->fetch_row()[0];$expired=(int)$con->query("SELECT COUNT(*) FROM pharmacy_medicines WHERE expiry_date IS NOT NULL AND expiry_date<CURDATE() AND quantity>0")->fetch_row()[0];$expiring=(int)$con->query("SELECT COUNT(*) FROM pharmacy_medicines WHERE expiry_date IS NOT NULL AND expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY)")->fetch_row()[0];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pharmacy</title><link rel="stylesheet" href="professional_assets/app.css"><link rel="stylesheet" href="professional_assets/theme.css.php"></head><body class="module-body"><div class="module-card pharmacy-page"><div class="module-head"><div><span class="eyebrow">PHARMACY & INVENTORY</span><h1>Pharmacy Management</h1><p class="muted">Manage medicines, incoming stock, outgoing dispensing, expiry and reorder levels.</p></div></div>
<?php if($msg):?><div class="success"><?php echo esc($msg);?></div><?php endif;?><?php if($error):?><div class="alert"><?php echo esc($error);?></div><?php endif;?>
<div class="pharmacy-kpis"><div><small>Total medicines</small><b><?php echo $total;?></b></div><div><small>Low stock</small><b><?php echo $low;?></b></div><div><small>Expired</small><b><?php echo $expired;?></b></div><div><small>Expiring ≤ 30 days</small><b><?php echo $expiring;?></b></div><div><small>Today's incoming</small><b><?php echo $incoming;?></b></div><div><small>Today's outgoing</small><b><?php echo $outgoing;?></b></div></div>
<div class="pharmacy-grid"><section class="panel"><h2>Add Medicine</h2><form method="post" class="form-grid"><input type="hidden" name="action" value="add_medicine"><label>Medicine name<input name="medicine_name" required></label><label>Generic name<input name="generic_name"></label><label>Category<input name="category" placeholder="Antibiotic, analgesic..." ></label><label>Dosage form<input name="dosage_form" placeholder="Tablet, syrup, injection..."></label><label>Strength<input name="strength" placeholder="500 mg"></label><label>Unit<input name="unit" value="unit"></label><label>Batch / Lot<input name="batch_no"></label><label>Expiry date<input type="date" name="expiry_date"></label><label>Purchase price<input type="number" step="0.01" min="0" name="purchase_price"></label><label>Selling price<input type="number" step="0.01" min="0" name="selling_price"></label><label>Opening quantity<input type="number" min="0" name="quantity" value="0"></label><label>Reorder level<input type="number" min="0" name="reorder_level" value="10"></label><label class="full">Supplier<input name="supplier"></label><button class="primary-btn full">Add medicine</button></form></section>
<section class="panel"><h2>Incoming / Outgoing</h2><form method="post" class="form-grid"><input type="hidden" name="action" value="stock"><label>Transaction<select name="transaction_type"><option value="incoming">Incoming / Purchase</option><option value="outgoing">Outgoing / Dispensing</option><option value="return">Return to stock</option><option value="adjustment">Stock adjustment</option></select></label><label>Medicine<select name="medicine_id" required><?php $m2=$con->query('SELECT id,medicine_name,batch_no,quantity FROM pharmacy_medicines ORDER BY medicine_name');while($m=$m2->fetch_assoc()):?><option value="<?php echo $m['id'];?>"><?php echo esc($m['medicine_name'].' — '.$m['batch_no'].' (stock '.$m['quantity'].')');?></option><?php endwhile;?></select></label><label>Quantity<input type="number" min="1" name="quantity" required></label><label>Unit price<input type="number" step="0.01" min="0" name="unit_price"></label><label>Patient (for outgoing)<select name="patient_id"><option value="0">Not linked</option><?php while($p=$patients->fetch_assoc()):?><option value="<?php echo $p['patientid'];?>"><?php echo esc($p['patientname']);?></option><?php endwhile;?></select></label><label>Supplier<input name="supplier"></label><label>Reference / Invoice<input name="reference_no"></label><label>Doctor<input name="doctor_name"></label><label>Prescription / Reference<input name="prescription_ref"></label><label>Note<textarea name="note" rows="2"></textarea></label><button class="primary-btn full">Save stock movement</button></form></section></div>
<section class="panel"><h2>Edit Medicine</h2><p class="muted">Select a medicine to update its details or use Delete in the stock table.</p><form method="post" class="pharmacy-filter"><input type="hidden" name="action" value="edit_medicine"><select name="id" required><?php $em=$con->query('SELECT id,medicine_name,batch_no FROM pharmacy_medicines ORDER BY medicine_name');while($e=$em->fetch_assoc()):?><option value="<?php echo $e['id'];?>"><?php echo esc($e['medicine_name'].' — '.$e['batch_no']);?></option><?php endwhile;?></select><input name="medicine_name" placeholder="Medicine name" required><input name="generic_name" placeholder="Generic name"><input name="category" placeholder="Category"><input name="dosage_form" placeholder="Dosage form"><input name="strength" placeholder="Strength"><input name="unit" placeholder="Unit"><input name="batch_no" placeholder="Batch / Lot"><input type="date" name="expiry_date"><input type="number" step="0.01" name="purchase_price" placeholder="Purchase price"><input type="number" step="0.01" name="selling_price" placeholder="Selling price"><input type="number" name="quantity" min="0" placeholder="Quantity"><input type="number" name="reorder_level" min="0" placeholder="Reorder level"><input name="supplier" placeholder="Supplier"><select name="status"><option>Active</option><option>Inactive</option></select><button class="secondary-btn">Update medicine</button></form></section>
<section class="panel"><h2>Categories & Suppliers</h2><div class="pharmacy-kpis"><div><small>Categories</small><b><?php echo (int)$con->query("SELECT COUNT(DISTINCT category) FROM pharmacy_medicines WHERE category<>''")->fetch_row()[0];?></b></div><div><small>Suppliers</small><b><?php echo (int)$con->query("SELECT COUNT(DISTINCT supplier) FROM pharmacy_medicines WHERE supplier<>''")->fetch_row()[0];?></b></div><div><small>Stock value</small><b><?php echo number_format((float)$con->query("SELECT COALESCE(SUM(quantity*purchase_price),0) FROM pharmacy_medicines")->fetch_row()[0],2);?></b></div><div><small>Today's sales</small><b><?php echo number_format((float)$con->query("SELECT COALESCE(SUM(t.quantity*m.selling_price),0) FROM pharmacy_transactions t JOIN pharmacy_medicines m ON m.id=t.medicine_id WHERE t.transaction_type='outgoing' AND DATE(t.transaction_date)=CURDATE()")->fetch_row()[0],2);?></b></div></div></section>
<section class="panel"><div class="filter-head"><div><h2>Medicine Stock</h2><p class="muted">Search by name, generic name, batch or supplier.</p></div><form class="pharmacy-filter"><select name="filter"><option value="all">All medicines</option><option value="low" <?php echo $filter==='low'?'selected':'';?>>Low stock</option><option value="expired" <?php echo $filter==='expired'?'selected':'';?>>Expired</option><option value="expiring" <?php echo $filter==='expiring'?'selected':'';?>>Expiring within 30 days</option></select><input name="search" value="<?php echo esc($search);?>" placeholder="Search medicine..."><button class="secondary-btn">Filter</button></form></div><div class="table-wrap"><table><thead><tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Stock</th><th>Reorder</th><th>Buy</th><th>Sell</th><th>Supplier</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($m=$meds->fetch_assoc()):$expiredRow=$m['expiry_date']&&$m['expiry_date']<date('Y-m-d');$lowRow=(int)$m['quantity']<=(int)$m['reorder_level'];?><tr><td><b><?php echo esc($m['medicine_name']);?></b><br><small><?php echo esc($m['generic_name']);?></small></td><td><?php echo esc($m['batch_no']);?></td><td><?php echo esc($m['expiry_date']??'');?></td><td><strong class="<?php echo $lowRow?'danger-text':'';?>"><?php echo (int)$m['quantity'];?></strong></td><td><?php echo (int)$m['reorder_level'];?></td><td><?php echo number_format((float)$m['purchase_price'],2);?></td><td><?php echo number_format((float)$m['selling_price'],2);?></td><td><?php echo esc($m['supplier']);?></td><td><?php echo $expiredRow?'Expired':($lowRow?'Low stock':'OK');?></td><td><a href="pharmacy.php?delete=<?php echo (int)$m['id'];?>" onclick="return confirm('Delete this medicine?');" style="color:#b42318">Delete</a></td></tr><?php endwhile;?></tbody></table></div></section>
<section class="panel"><h2>Recent Stock Movements</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Medicine</th><th>Qty</th><th>Patient</th><th>Reference</th><th>By</th></tr></thead><tbody><?php $r=$con->query("SELECT t.*,m.medicine_name,COALESCE(p.patientname,'') patientname FROM pharmacy_transactions t JOIN pharmacy_medicines m ON m.id=t.medicine_id LEFT JOIN patient p ON p.patientid=t.patient_id ORDER BY t.id DESC LIMIT 30");while($x=$r->fetch_assoc()):?><tr><td><?php echo esc($x['transaction_date']);?></td><td><?php echo ucfirst(esc($x['transaction_type']));?></td><td><?php echo esc($x['medicine_name']);?></td><td><?php echo (int)$x['quantity'];?></td><td><?php echo esc($x['patientname']);?></td><td><?php echo esc($x['reference_no']);?></td><td><?php echo esc($x['created_by']);?></td></tr><?php endwhile;?></tbody></table></div></section>
</div></body></html>
