<?php
session_start(); include("headers.php"); include("dbconnection.php");
if(isset($_GET['delid'])){ $id=(int)$_GET['delid']; $qsql=mysqli_query($con,"DELETE FROM doctor WHERE doctorid=$id"); if(mysqli_affected_rows($con)==1) echo "<script>alert('Doctor record deleted successfully.');</script>"; }
$filter=$_GET['filter']??'name'; $search=trim($_GET['search']??''); $allowed=['name','id','department','phone','status']; if(!in_array($filter,$allowed,true))$filter='name';
$where='1=1'; $param='';
if($search!==''){ $safe=mysqli_real_escape_string($con,$search); if($filter==='name')$where.=" AND doctorname LIKE '%$safe%'"; elseif($filter==='id'&&ctype_digit($search))$where.=" AND doctorid=".(int)$search; elseif($filter==='department')$where.=" AND departmentid IN (SELECT departmentid FROM department WHERE departmentname LIKE '%$safe%')"; elseif($filter==='phone')$where.=" AND mobileno LIKE '%$safe%'"; elseif($filter==='status')$where.=" AND status='$safe'"; }
$sql="SELECT d.*,COALESCE(dp.departmentname,'') departmentname FROM doctor d LEFT JOIN department dp ON dp.departmentid=d.departmentid WHERE $where ORDER BY d.doctorname"; $qsql=mysqli_query($con,$sql);
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctors</title></head><body><div class="wrapper col4"><div id="container"><h1>Doctors</h1><form method="get" class="doctor-filter"><label>Search filter<select name="filter"><option value="name" <?= $filter==='name'?'selected':'' ?>>Doctor Name</option><option value="id" <?= $filter==='id'?'selected':'' ?>>Doctor ID</option><option value="department" <?= $filter==='department'?'selected':'' ?>>Department</option><option value="phone" <?= $filter==='phone'?'selected':'' ?>>Phone Number</option><option value="status" <?= $filter==='status'?'selected':'' ?>>Status</option></select></label><label>Search<input type="search" name="search" value="<?= htmlspecialchars($search) ?>" placeholder="Search selected field..."></label><button type="submit">Filter</button><a href="viewdoctor.php" style="display:inline-block;padding:12px 16px;border-radius:10px;text-decoration:none;border:1px solid #d8dfeb;margin-top:7px">Reset</a></form><div style="height:20px"></div><div style="overflow:auto"><table id="doctor"><thead><tr><th>Doctor Name</th><th>Mobile</th><th>Department</th><th>Login ID</th><th>Consultancy</th><th>Education</th><th>Experience</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($rs=mysqli_fetch_assoc($qsql)): ?><tr><td><?= htmlspecialchars($rs['doctorname']) ?></td><td><?= htmlspecialchars($rs['mobileno']) ?></td><td><?= htmlspecialchars($rs['departmentname']) ?></td><td><?= htmlspecialchars($rs['loginid']) ?></td><td><?= htmlspecialchars($rs['consultancy_charge']) ?></td><td><?= htmlspecialchars($rs['education']) ?></td><td><?= htmlspecialchars($rs['experience']) ?></td><td><?= htmlspecialchars($rs['status']) ?></td><td><a href="doctor.php?editid=<?= (int)$rs['doctorid'] ?>">Edit</a> | <a href="viewdoctor.php?delid=<?= (int)$rs['doctorid'] ?>" onclick="return confirm('Delete this doctor? This action cannot be undone.');" style="color:#b42318">Delete</a></td></tr><?php endwhile; ?></tbody></table></div></div></div></body></html>
