<?php
session_start(); include("headers.php"); include("dbconnection.php");
if(isset($_GET['delid'])){ $id=(int)$_GET['delid']; mysqli_query($con,"DELETE FROM patient WHERE patientid=$id"); }
$filter=$_GET['filter']??'name';$search=trim($_GET['search']??'');$status=$_GET['admission_status']??'all';
$allowed=['name','id','phone','gender','admission_date','admission_status'];if(!in_array($filter,$allowed,true))$filter='name';$where='1=1';$safe=mysqli_real_escape_string($con,$search);
if($search!==''){if($filter==='name')$where.=" AND patientname LIKE '%$safe%'";elseif($filter==='id'&&ctype_digit($search))$where.=' AND patientid='.(int)$search;elseif($filter==='phone')$where.=" AND mobileno LIKE '%$safe%'";elseif($filter==='gender')$where.=" AND gender LIKE '%$safe%'";elseif($filter==='admission_date')$where.=" AND admissiondate LIKE '%$safe%'";}
// Admission status is supported when the installation has an admission field/table; otherwise active status is used as a safe fallback.
if($filter==='admission_status'&&$status!=='all'){$where.=" AND status='".mysqli_real_escape_string($con,$status)."'";}
$q=mysqli_query($con,"SELECT * FROM patient WHERE $where ORDER BY patientname");
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Patients</title></head><body><div class="wrapper col4"><div id="container"><h1>Patients</h1><form method="get"><label>Search filter<select name="filter"><option value="name" <?= $filter==='name'?'selected':'' ?>>Patient Name</option><option value="id" <?= $filter==='id'?'selected':'' ?>>Patient ID</option><option value="phone" <?= $filter==='phone'?'selected':'' ?>>Phone Number</option><option value="gender" <?= $filter==='gender'?'selected':'' ?>>Gender</option><option value="admission_date" <?= $filter==='admission_date'?'selected':'' ?>>Admission Date</option><option value="admission_status" <?= $filter==='admission_status'?'selected':'' ?>>Admission Status</option></select></label><label>Search<input type="search" name="search" value="<?= htmlspecialchars($search) ?>" placeholder="Search selected field..."></label><label>Admission status<select name="admission_status"><option value="all">All</option><option value="Active" <?= $status==='Active'?'selected':'' ?>>Admitted / Active</option><option value="Inactive" <?= $status==='Inactive'?'selected':'' ?>>Not admitted / Inactive</option></select></label><button type="submit">Filter</button><a href="viewpatient.php" style="display:inline-block;padding:12px 16px;border-radius:10px;text-decoration:none;border:1px solid #d8dfeb;margin-top:7px">Reset</a></form><div style="height:20px"></div><div style="overflow:auto"><table id="patient"><thead><tr><th>ID</th><th>Patient Name</th><th>Mobile</th><th>Gender</th><th>Admission Date</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($r=mysqli_fetch_assoc($q)): ?><tr><td><?= (int)$r['patientid'] ?></td><td><?= htmlspecialchars($r['patientname']??'') ?></td><td><?= htmlspecialchars($r['mobileno']??'') ?></td><td><?= htmlspecialchars($r['gender']??'') ?></td><td><?= htmlspecialchars($r['admissiondate']??'') ?></td><td><?= htmlspecialchars($r['status']??'') ?></td><td><a href="patient.php?editid=<?= (int)$r['patientid'] ?>">Edit</a> | <a href="viewpatient.php?delid=<?= (int)$r['patientid'] ?>" onclick="return confirm('Delete this patient?');" style="color:#b42318">Delete</a></td></tr><?php endwhile; ?></tbody></table></div></div></div></body></html>
