document.addEventListener('DOMContentLoaded',()=>{
 const body=document.body,savedTheme=localStorage.getItem('hms-theme')||'light',lang=localStorage.getItem('hms-lang')||'en';
 body.dataset.theme=savedTheme;
 const setDirection=()=>{const rtl=['ps','fa'].includes(localStorage.getItem('hms-lang')||'en');document.documentElement.dir=rtl?'rtl':'ltr';document.documentElement.classList.toggle('rtl-mode',rtl);body.classList.toggle('rtl-mode',rtl);body.setAttribute('dir',rtl?'rtl':'ltr');};
 setDirection();
 document.querySelectorAll('#themeBtn').forEach(btn=>btn.addEventListener('click',()=>{const next=body.dataset.theme==='dark'?'light':'dark';body.dataset.theme=next;localStorage.setItem('hms-theme',next);}));
 document.querySelectorAll('#languageSelect').forEach(s=>{s.value=lang;s.addEventListener('change',()=>{localStorage.setItem('hms-lang',s.value);setDirection();location.reload();});});
 const sidebar=document.getElementById('sidebar'),menu=document.getElementById('mobileMenu'),dash=document.getElementById('dashboardView'),work=document.getElementById('workspace'),frame=document.getElementById('moduleFrame'),title=document.getElementById('pageTitle'),workspaceTitle=document.getElementById('workspaceTitle'),loading=document.querySelector('.workspace-loading'),exportBtn=document.getElementById('exportBtn');
 const names={'viewpatient.php':'patients','patient.php':'patientProfile','patientprofile.php':'patientProfile','patientappointment.php':'patientAppointments','viewdoctor.php':'doctors','doctorprofile.php':'doctorProfile','doctortimings.php':'doctorSchedule','department.php':'departments','departmentDoctor.php':'departmentDoctors','viewappointment.php':'appointments','appointmentapproval.php':'appointmentApproval','medicine.php':'pharmacy','viewtreatmentrecord.php':'treatments','prescription.php':'prescriptions','appointment.php':'bookAppointment','patient-health.php':'healthRecord','patientprescription.php':'prescriptions','orders.php':'patientOrders','pharmacy.php':'pharmacy','finance.php':'financeFees','settings.php':'hospitalSettings','profile-settings.php':'myProfile','attendance.php':'attendance','workers.php':'workers','backup.php':'backup'};
 const exportTables={'viewpatient.php':'patient','patient.php':'patient','patientprofile.php':'patient','patientappointment.php':'appointment','viewdoctor.php':'doctor','doctorprofile.php':'doctor','doctortimings.php':'doctor_timings','department.php':'department','departmentDoctor.php':'doctor','viewappointment.php':'appointment','appointmentapproval.php':'appointment','medicine.php':'medicine','viewtreatmentrecord.php':'treatment_records','prescription.php':'prescription','appointment.php':'appointment','patient-health.php':'treatment_records','patientprescription.php':'prescription','orders.php':'orders','finance.php':'financial_transactions','attendance.php':'attendance','workers.php':'workers'};
 menu?.addEventListener('click',()=>sidebar.classList.toggle('open'));
 function openModule(url){
   if(!url||url==='dashboard'){dash.hidden=false;work.hidden=true;title.textContent=(window.HMS_I18N?.d.dashboard)||'Dashboard';if(exportBtn)exportBtn.style.display='none';document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));document.querySelector('[data-view="dashboard"]')?.classList.add('active');return;}
   dash.hidden=true;work.hidden=false;const baseUrl=url.split('?')[0]; const key=names[baseUrl];const translated=key&&window.HMS_I18N?.d[key];title.textContent=translated||key||'Hospital Module';if(workspaceTitle)workspaceTitle.textContent=translated||key||'Hospital Module';if(exportBtn){const table=exportTables[baseUrl];exportBtn.style.display=table?'inline-flex':'none';if(table)exportBtn.href='export.php?table='+encodeURIComponent(table);}
   if(loading)loading.style.display='grid';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===url));frame.src=url;frame.onload=()=>{if(loading)loading.style.display='none';window.HMS_translateFrame?.(frame);};sidebar?.classList.remove('open');
 }
 document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openModule(el.dataset.view)}));
});
